language: python
python: 3.5
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install: "pip install Lektor"
script: "lektor build -f webpack"
deploy:
  provider: script
  script: "lektor deploy ghpages"
  on:
    branch: master