name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag folyd-image:latest
    - name: Push Docker image to Github Packages
      run: |
         docker login docker.pkg.github.com --username folyd -p ${{ secrets.GITHUB_TOKEN }}
         docker tag folyd-image docker.pkg.github.com/folyd/folyd.com/folyd-image:latest
         docker push docker.pkg.github.com/folyd/folyd.com/folyd-image:latest
