name: Deploy

on: 
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install lektor
      run: |
        python -m pip install --upgrade pip
        pip install lektor
    - name: Build lektor
      run: lektor build -f webpack
    - name: Deploy to Github pages
      run: lektor deploy ghpages
